#返回前台配置
spring:
  mvc:
    view:
      suffix: /
      prefix: .html
  thymeleaf:
    cache: false
  #热部署
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      additional-exclude: static
  #数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/hwy_company?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

#项目路径
server:
  servlet:
    context-path: /

#mybatis的扫描配置
mybatis:
  type-aliases-package: com.hwy.demo.dao
  mapper-locations: classpath:mapper/*.xml

uploadPath: C:/upload/img

sys:
  username: admin
  pass: admin
